Handle Create Database

diff --git a/CreateTable b/CreateTable
--- a/CreateTable
+++ b/CreateTable
@@ -1,101 +1,84 @@
 #!/bin/bash
 source ./Validations
+source ./Common
 
 #declare flag variable to check sucess of operations
-flag = 1
+flag=1
 
-function set_primary_key() {
-
-
-    echo "You have defined the following columns:"
-    awk -F: '{print $1}' "$metadata_file"
-    # Step 2: Display the columns
-    for ((i=0; i<num_columns; i++))
-    do
-        echo "$((i+1)). ${columns[$i]} (${column_types[$i]})"
-    done
-    echo "Enter the primary key column name: "
-    read primary_key_choice
-
-
-    # Step 3: Ask the user to select a column number for the primary key
-    echo "Please enter the number of the column to be the primary key: "
-    read pk_number
-    
-    # Step 4: Validate the primary key selection
-    if [[ "$pk_number" -ge 1 && "$pk_number" -le "$num_columns" ]]; then
-        echo "You have selected ${columns[$((pk_number-1))]} as the primary key."
-    else
-        echo "Invalid selection. Please select a number between 1 and $num_columns."
-        flag = 0
-    fi
-
-    # Update the metadata file to mark the primary key
-    awk -F: -v pk="$primary_key" '{
-        if ($1 == pk && $0 !~ /:PK$/) {
-            $0 = $0 ":PK"
-        }
-        print
-    }' "$metadata_file" > "${metadata_file}.tmp" && mv "${metadata_file}.tmp" "$metadata_file"
-
-    echo "Primary key '$primary_key' has been set successfully in '$metadata_file'."
-}
 function create_table() {
-    echo "**Enter the name of the table: "
-    read tblName
+    read -p ">>Enter table name: " tblName
     if ! is_empty_input "$tblName" && ! is_already_exists_file "$tblName" && ! is_invalid_name "$tblName" ; then
-        echo "Table name '$tblName' is valid.------------------"
+        echo "Table name '$tblName' is valid------------------"
         echo "Continuing---------------------------------------"
-        flag = 1
+        flag=1
     else
-        flag = 0
-        echo "Failed validation checks......."
+        flag=0
         create_table
     fi
 
-    if flag == 1; then
+    if [ $flag -eq 1 ]; then
         # Input number of columns-------------------------------
-        echo "**Enter the number of columns in your table: "
-        read colNum
-        if ! is_empty_input '$colNum' && ! is_less_than_zero '$colNum'; then
+        read -p ">>Enter the number of columns in your table: " colNum
 
+        if ! is_empty_input $colNum && ! is_less_than_zero $colNum; then
             echo "files '$tblName' , '$tblName'.metadata created for the table creation..."
-            touch "$tblName" "$tblName.metadata" #create datafile and metadata file
+            touch "$tblName" "$tblName.metadata"
 
             echo "Number of columns '$colNum' is valid."
             echo "Continuing-----------------------------------"
-
+            sleep 0.5
+            flag=1
+            create_columns
         else
             echo "Failed validation checks......."
-            flag = 0
+            flag=0
             create_table
         fi  
     fi
+}
 
-    if flag == 1; then
-    # Input column names and datatypes-----------------------
-    for i in $(seq 1 "$colNum"); #loop through the number of columns
-    do
-        echo "**Enter column name $i followed by [space] and column datatype (int/string):  eg: name string"
+function create_columns() {
+    #adding PK column
+    if [ $flag -eq 1 ]; then
+        echo ">>Enter column name 1 (PRIMARY KEY column) followed by datatype (int/string):  eg:id int "
         read colName colType
         if ! is_empty_input "$colName" && ! is_invalid_name "$colName" &&  \
         ! is_empty_input "$colType" && ! is_invalid_datatype "$colType" && \
         ! is_duplicate_column "$colName" "$tblName.metadata" ; then
-            echo "Passed validation checks for column '$colName'......."
-            echo "Creating column '$colName' with datatype '$colType' in table '$tblName'..."
-            echo "$colName:$colType" >> "$tblName.metadata"
+            echo "$colName:$colType:PK" >> "$tblName.metadata"
+            flag=1
         else
-            echo "Failed validation checks......."
-            flag = 0
+            echo "Failed validation checks. Aborting table creation..."
+            rm "$tblName" "$tblName.metadata"
+            flag=0
+            navigate_menu
+        fi
+    fi
+
+    if [ $flag -eq 1 ]; then
+    for ((i=2; i<$colNum+1; i++)) #loop through the number of columns -1 
+    do
+        echo ">>Enter column name $i followed by datatype (int/string):  eg: name string"
+        read colName colType
+        if ! is_empty_input "$colName" && ! is_invalid_name "$colName" &&  \
+        ! is_empty_input "$colType" && ! is_invalid_datatype "$colType" && \
+        ! is_duplicate_column "$colName" "$tblName.metadata" ; then
+            echo "$colName:$colType" >> "$tblName.metadata"
+            flag=1
+        else
+            echo "Failed validation checks. Aborting table creation..."
+            rm "$tblName" "$tblName.metadata"
+            navigate_menu
         fi
     done
     fi
-
-    if flag == 1; then;
-        set_primary_key "$$tblName.metadata"
+    if [ $flag -eq 1 ]; then
+        echo "Table '$tblName' created successfully."
+        navigate_menu
     fi
 }
+    
 
 #temp code for testing .. delete later
-cd NewDB
+cd Database/DB1
 create_table
