fixes

diff --git a/CreateTable b/CreateTable
--- a/CreateTable
+++ b/CreateTable
@@ -11,7 +11,7 @@ function set_primary_key() {
     echo "**Enter the name of the column to set as the primary key:"
     read primary_key
 
-    # Check if the column exists in the metadata file
+
     if ! awk -F: -v pk="$primary_key" '$1 == pk {found=1} END {exit !found}' "$metadata_file"; then
         echo "Warning: Column '$primary_key' not found in metadata."
         exit 1
@@ -33,6 +33,14 @@ function create_table() {
     if ! is_empty_input "$tblName" && ! is_already_exists_file "$tblName" && ! is_invalid_name "$tblName" ; then
         echo "Table name '$tblName' is valid.------------------"
         echo "Continuing---------------------------------------"
+        flag = 1
+    else
+        flag = 0
+        echo "Failed validation checks......."
+        create_table
+    fi
+
+    if flag == 1; then
         # Input number of columns-------------------------------
         echo "**Enter the number of columns in your table: "
         read colNum
@@ -43,28 +51,33 @@ function create_table() {
 
             echo "Number of columns '$colNum' is valid."
             echo "Continuing-----------------------------------"
-            for i in $(seq 1 "$colNum"); #loop through the number of columns
-            do
-                echo "**Enter the name of column $i followed by its datatype (int/string/float):  eg: name string"
-                read colName colType
-                if ! is_empty_input "$colName" && ! is_invalid_name "$colName" &&  \
-                ! is_empty_input "$colType" && ! is_invalid_datatype "$colType" && \
-                ! is_duplicate_column "$colName" "$tblName.metadata" ; then
-                    echo "Passed validation checks for column '$colName'......."
-                    echo "Creating column '$colName' with datatype '$colType' in table '$tblName'..."
-                    echo "$colName:$colType" >> "$tblName.metadata"
-                else
-                    echo "Failed validation checks......."
-                    flag = 0
-                    exit 1
-                fi
-            done
+
+        else
+            echo "Failed validation checks......."
+            flag = 0
+            create_table
+        fi  
+    fi
+
+    if flag == 1; then
+    # Input column names and datatypes-----------------------
+    for i in $(seq 1 "$colNum"); #loop through the number of columns
+    do
+        echo "**Enter column name $i followed by [space] and column datatype (int/string):  eg: name string"
+        read colName colType
+        if ! is_empty_input "$colName" && ! is_invalid_name "$colName" &&  \
+        ! is_empty_input "$colType" && ! is_invalid_datatype "$colType" && \
+        ! is_duplicate_column "$colName" "$tblName.metadata" ; then
+            echo "Passed validation checks for column '$colName'......."
+            echo "Creating column '$colName' with datatype '$colType' in table '$tblName'..."
+            echo "$colName:$colType" >> "$tblName.metadata"
         else
             echo "Failed validation checks......."
             flag = 0
         fi
-    fi 
-    #----------------------------------------------------------------------------------
+    done
+    fi
+
     if flag == 1; then;
         set_primary_key "$tblName"
     fi
